/* ============================================================
   Bloom · Product dataset (auto-generated from images/aclothes)
   Regenerate with: node scripts/build-catalog.js
   ============================================================ */

;(function () {
  'use strict';

  const PRODUCTS = [
    {
      id: "maryjanes-burgundy",
      name: "Burgundy Patent Slingback Mary Janes",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Heels",
      price: 6140,
      originalPrice: 8220,
      rating: 4.7,
      reviews: 64,
      popularity: 78,
      isNew: true,
      tags: ["vintage","patent","kitten-heel"],
      colors: ["Burgundy","Black"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8"],
      images: ["images/aclothes/maryjanes-burgundy.jpg"],
      description: "Burgundy Patent Slingback Mary Janes · handcrafted heels, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "alibox-gift-bundle",
      name: "Embroidered Black Lace Shoes",
      brand: "Swadeshi Wares",
      category: "shoes",
      subcategory: "Flats",
      price: 2980,
      originalPrice: null,
      rating: 4.6,
      reviews: 41,
      popularity: 44,
      isNew: false,
      tags: ["embroidered","lace","black"],
      colors: ["Black"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8"],
      images: ["images/aclothes/alibox-gift-bundle.jpg"],
      description: "Embroidered Black Lace Shoes · handcrafted flats, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "vangogh-sunflower-earrings",
      name: "Van Gogh Sunflower Earrings",
      brand: "Atelier Moti",
      category: "jewellery",
      subcategory: "Earrings",
      price: 3480,
      originalPrice: 4640,
      rating: 4.8,
      reviews: 87,
      popularity: 81,
      isNew: true,
      tags: ["hand-painted","art","statement"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/vangogh-sunflower-earrings.jpg"],
      description: "Van Gogh Sunflower Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "bleach-tank-top",
      name: "Bleach Design Tank Top",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Tops",
      price: 2000,
      originalPrice: 2820,
      rating: 4.4,
      reviews: 52,
      popularity: 66,
      isNew: false,
      tags: ["bleach","summer","streetwear"],
      colors: ["White"],
      sizes: ["34","36","38"],
      images: ["images/aclothes/bleach-tank-top.jpg"],
      description: "Bleach Design Tank Top · handcrafted tops, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "comfort-cream-crop-tee",
      name: "Block-Printed Cream Crop Tee",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Tops",
      price: 2660,
      originalPrice: null,
      rating: 4.6,
      reviews: 128,
      popularity: 74,
      isNew: true,
      tags: ["block-print","cotton","crop"],
      colors: ["Cream","Blue"],
      sizes: ["34","36","38","40"],
      images: ["images/aclothes/comfort-cream-crop-tee.jpg"],
      description: "Block-Printed Cream Crop Tee · handcrafted tops, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "kolhapuri-sandals",
      name: "Earthy Kolhapuri Sandals",
      brand: "Kolhapur Collective",
      category: "shoes",
      subcategory: "Sandals",
      price: 3160,
      originalPrice: 4320,
      rating: 4.9,
      reviews: 302,
      popularity: 93,
      isNew: true,
      tags: ["handmade","leather","traditional"],
      colors: ["Tan","Maroon"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8","UK 9"],
      images: ["images/aclothes/kolhapuri-sandals.jpg"],
      description: "Earthy Kolhapuri Sandals · handcrafted sandals, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "green-quilling-jhumka",
      name: "Green Quilled Jhumka Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 1500,
      originalPrice: null,
      rating: 4.7,
      reviews: 118,
      popularity: 88,
      isNew: false,
      tags: ["quilling","jhumka","paper-art"],
      colors: ["Green"],
      sizes: ["One Size"],
      images: ["images/aclothes/green-quilling-jhumka.jpg"],
      description: "Green Quilled Jhumka Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "guitar-bleach-tank",
      name: "Hand-Bleached Guitar Tank",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Tops",
      price: 2160,
      originalPrice: null,
      rating: 4.3,
      reviews: 37,
      popularity: 52,
      isNew: false,
      tags: ["bleach","streetwear","graphic"],
      colors: ["Black"],
      sizes: ["34","36","38"],
      images: ["images/aclothes/guitar-bleach-tank.jpg"],
      description: "Hand-Bleached Guitar Tank · handcrafted tops, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "dragonfly-arm-cuff",
      name: "Handmade Dragonfly Arm Cuff",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Cuffs",
      price: 2400,
      originalPrice: null,
      rating: 4.7,
      reviews: 93,
      popularity: 70,
      isNew: true,
      tags: ["wire-wrap","handmade","boho"],
      colors: ["Antique Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/dragonfly-arm-cuff.jpg"],
      description: "Handmade Dragonfly Arm Cuff · handcrafted cuffs, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "handpainted-wide-jeans",
      name: "Hand-Painted Wide Denim Jeans",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 4820,
      originalPrice: 6300,
      rating: 4.5,
      reviews: 49,
      popularity: 68,
      isNew: true,
      tags: ["hand-painted","denim","one-of-one"],
      colors: ["Indigo"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/handpainted-wide-jeans.jpg"],
      description: "Hand-Painted Wide Denim Jeans · handcrafted jeans, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "moon-sun-jeans",
      name: "Moon & Sun Painted Jeans",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 5140,
      originalPrice: 6980,
      rating: 4.8,
      reviews: 143,
      popularity: 91,
      isNew: false,
      tags: ["painted","celestial","denim"],
      colors: ["Washed Blue"],
      sizes: ["34","36","38","40"],
      images: ["images/aclothes/moon-sun-jeans.jpg"],
      description: "Moon & Sun Painted Jeans · handcrafted jeans, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "cherry-earrings",
      name: "Quilled Cherry Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 1240,
      originalPrice: null,
      rating: 4.6,
      reviews: 77,
      popularity: 59,
      isNew: false,
      tags: ["quilling","fruit","playful"],
      colors: ["Red"],
      sizes: ["One Size"],
      images: ["images/aclothes/cherry-earrings.jpg"],
      description: "Quilled Cherry Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "spiral-pendant-necklace",
      name: "Spiral Swirl Pendant Necklace",
      brand: "Estrella",
      category: "jewellery",
      subcategory: "Necklaces",
      price: 2820,
      originalPrice: 3740,
      rating: 4.6,
      reviews: 88,
      popularity: 75,
      isNew: true,
      tags: ["minimal","silver","unisex"],
      colors: ["Silver"],
      sizes: ["One Size"],
      images: ["images/aclothes/spiral-pendant-necklace.jpg"],
      description: "Spiral Swirl Pendant Necklace · handcrafted necklaces, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "bohemian-linen-dress",
      name: "Bohemian Pure Linen Shirt",
      brand: "Boho Threads",
      category: "clothing",
      subcategory: "Shirts",
      price: 4820,
      originalPrice: 6480,
      rating: 4.8,
      reviews: 176,
      popularity: 89,
      isNew: true,
      tags: ["linen","shirt","handmade"],
      colors: ["Beige","Green"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/bohemian-linen-dress.jpg"],
      description: "Bohemian Pure Linen Shirt · handcrafted shirts, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "collectors-ceramic-vessel",
      name: "Ceramic Earrings",
      brand: "Terracotta Tales",
      category: "jewellery",
      subcategory: "Earrings",
      price: 3660,
      originalPrice: null,
      rating: 4.5,
      reviews: 61,
      popularity: 47,
      isNew: false,
      tags: ["ceramic","earrings","handmade"],
      colors: ["Terracotta","Cream"],
      sizes: ["One Size"],
      images: ["images/aclothes/collectors-ceramic-vessel.jpg"],
      description: "Ceramic Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "tiger-eye-shirt",
      name: "Tiger Eye Statement Shirt",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Shirts",
      price: 3740,
      originalPrice: 4820,
      rating: 4.6,
      reviews: 94,
      popularity: 79,
      isNew: true,
      tags: ["printed","oversized","statement"],
      colors: ["Multicolour"],
      sizes: ["34","36","38"],
      images: ["images/aclothes/tiger-eye-shirt.jpg"],
      description: "Tiger Eye Statement Shirt · handcrafted shirts, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "tiger-graphic-tee",
      name: "Tiger Graphic Tee",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Tees",
      price: 2320,
      originalPrice: null,
      rating: 4.4,
      reviews: 58,
      popularity: 63,
      isNew: false,
      tags: ["graphic","streetwear"],
      colors: ["Black"],
      sizes: ["34","36","38","40"],
      images: ["images/aclothes/tiger-graphic-tee.jpg"],
      description: "Tiger Graphic Tee · handcrafted tees, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "bleach-streetwear-tee",
      name: "Trendy Bleach Crop Top",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Tops",
      price: 3160,
      originalPrice: null,
      rating: 4.3,
      reviews: 41,
      popularity: 51,
      isNew: false,
      tags: ["bleach","crop","streetwear"],
      colors: ["Black"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/bleach-streetwear-tee.jpg"],
      description: "Trendy Bleach Crop Top · handcrafted tops, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "embroidered-slip-dress",
      name: "Wire Earrings",
      brand: "Estrella",
      category: "jewellery",
      subcategory: "Earrings",
      price: 1660,
      originalPrice: 2320,
      rating: 4.6,
      reviews: 66,
      popularity: 72,
      isNew: false,
      tags: ["wire","earrings","minimal"],
      colors: ["Silver","Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/embroidered-slip-dress.jpg"],
      description: "Wire Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "chanderi-co-ord",
      name: "Spiderman Sneakers",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Sneakers",
      price: 3740,
      originalPrice: 4820,
      rating: 4.6,
      reviews: 121,
      popularity: 84,
      isNew: true,
      tags: ["sneakers","graphic","streetwear"],
      colors: ["Black","Red"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8","UK 9","UK 10"],
      images: ["images/aclothes/chanderi-co-ord.jpg"],
      description: "Spiderman Sneakers · handcrafted sneakers, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "handloom-silk-saree",
      name: "Clay Earrings",
      brand: "Atelier Moti",
      category: "jewellery",
      subcategory: "Earrings",
      price: 2000,
      originalPrice: 2820,
      rating: 4.7,
      reviews: 98,
      popularity: 87,
      isNew: false,
      tags: ["clay","earrings","handmade"],
      colors: ["Terracotta","Cream"],
      sizes: ["One Size"],
      images: ["images/aclothes/handloom-silk-saree.jpg"],
      description: "Clay Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "ankle-strap-flats",
      name: "Embroidered Ankle-Strap Boots",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Boots",
      price: 3820,
      originalPrice: null,
      rating: 4.5,
      reviews: 54,
      popularity: 60,
      isNew: true,
      tags: ["boots","embroidered","ankle"],
      colors: ["Black","Gold"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8"],
      images: ["images/aclothes/ankle-strap-flats.jpg"],
      description: "Embroidered Ankle-Strap Boots · handcrafted boots, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "indigo-block-print-dress",
      name: "Indigo Block-Print Shirt",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Shirts",
      price: 4320,
      originalPrice: 5820,
      rating: 4.6,
      reviews: 88,
      popularity: 76,
      isNew: false,
      tags: ["block-print","shirt","indigo"],
      colors: ["Indigo"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/indigo-block-print-dress.jpg"],
      description: "Indigo Block-Print Shirt · handcrafted shirts, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "satin-slip-dress",
      name: "Hand-Painted Dystopian T-Shirt",
      brand: "Estrella",
      category: "clothing",
      subcategory: "Tees",
      price: 5320,
      originalPrice: null,
      rating: 4.6,
      reviews: 73,
      popularity: 71,
      isNew: true,
      tags: ["hand-painted","graphic","tee"],
      colors: ["Multicolour"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/satin-slip-dress.jpg"],
      description: "Hand-Painted Dystopian T-Shirt · handcrafted tees, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "co-ord-lounge-set",
      name: "Cotton Lounge Shirt",
      brand: "IndiMade",
      category: "clothing",
      subcategory: "Shirts",
      price: 3980,
      originalPrice: null,
      rating: 4.5,
      reviews: 82,
      popularity: 55,
      isNew: false,
      tags: ["lounge","shirt","cotton"],
      colors: ["Cream"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/co-ord-lounge-set.jpg"],
      description: "Cotton Lounge Shirt · handcrafted shirts, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "printed-midi-skirt",
      name: "Block-Printed Jeans",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 3320,
      originalPrice: 4480,
      rating: 4.5,
      reviews: 47,
      popularity: 67,
      isNew: false,
      tags: ["block-print","jeans","denim"],
      colors: ["Indigo"],
      sizes: ["26","28","30","32","34"],
      images: ["images/aclothes/printed-midi-skirt.jpg"],
      description: "Block-Printed Jeans · handcrafted jeans, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "chunky-bead-bracelet",
      name: "Sunflower-Pattern Denim Jeans",
      brand: "Kala Kendra",
      category: "clothing",
      subcategory: "Jeans",
      price: 1320,
      originalPrice: null,
      rating: 4.4,
      reviews: 39,
      popularity: 49,
      isNew: false,
      tags: ["sunflower","jeans","denim"],
      colors: ["Blue"],
      sizes: ["26","28","30","32","34"],
      images: ["images/aclothes/chunky-bead-bracelet.jpg"],
      description: "Sunflower-Pattern Denim Jeans · handcrafted jeans, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "knotted-silk-band",
      name: "Dragonfly Earrings",
      brand: "Swadeshi Wares",
      category: "jewellery",
      subcategory: "Earrings",
      price: 1000,
      originalPrice: null,
      rating: 4.5,
      reviews: 72,
      popularity: 57,
      isNew: true,
      tags: ["dragonfly","earrings","boho"],
      colors: ["Antique Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/knotted-silk-band.jpg"],
      description: "Dragonfly Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "matte-hoop-earrings",
      name: "Hand-Painted Sneakers",
      brand: "Estrella",
      category: "shoes",
      subcategory: "Sneakers",
      price: 1580,
      originalPrice: null,
      rating: 4.6,
      reviews: 91,
      popularity: 62,
      isNew: false,
      tags: ["sneakers","hand-painted","custom"],
      colors: ["White","Multicolour"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8","UK 9","UK 10"],
      images: ["images/aclothes/matte-hoop-earrings.jpg"],
      description: "Hand-Painted Sneakers · handcrafted sneakers, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "beaded-flower-earrings",
      name: "Beaded Flower Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 1820,
      originalPrice: null,
      rating: 4.7,
      reviews: 104,
      popularity: 85,
      isNew: true,
      tags: ["floral","beaded","handmade"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/beaded-flower-earrings.jpg"],
      description: "Beaded Flower Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "spiderman-custom-tee",
      name: "Custom Spider Jeans",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Jeans",
      price: 2240,
      originalPrice: null,
      rating: 4.2,
      reviews: 44,
      popularity: 48,
      isNew: false,
      tags: ["custom","jeans","graphic"],
      colors: ["Indigo"],
      sizes: ["26","28","30","32","34"],
      images: ["images/aclothes/spiderman-custom-tee.jpg"],
      description: "Custom Spider Jeans · handcrafted jeans, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "diy-painted-jorts",
      name: "DIY Painted Denim Jorts",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 2820,
      originalPrice: null,
      rating: 4.5,
      reviews: 58,
      popularity: 58,
      isNew: true,
      tags: ["painted","jorts","summer"],
      colors: ["Indigo"],
      sizes: ["34","36","38"],
      images: ["images/aclothes/diy-painted-jorts.jpg"],
      description: "DIY Painted Denim Jorts · handcrafted jeans, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "bafta-embroidered-top",
      name: "Dual-Color Handbag",
      brand: "IndiMade",
      category: "bags",
      subcategory: "Handbags",
      price: 3240,
      originalPrice: null,
      rating: 4.4,
      reviews: 37,
      popularity: 50,
      isNew: false,
      tags: ["handbag","dual-tone","everyday"],
      colors: ["Black","Tan"],
      sizes: ["One Size"],
      images: ["images/aclothes/bafta-embroidered-top.jpg"],
      description: "Dual-Color Handbag · handcrafted handbags, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "blue-satin-drape-tank",
      name: "Blue Satin Drape Tank",
      brand: "Estrella",
      category: "clothing",
      subcategory: "Tops",
      price: 2740,
      originalPrice: 3660,
      rating: 4.6,
      reviews: 69,
      popularity: 73,
      isNew: true,
      tags: ["satin","drape","going-out"],
      colors: ["Cobalt"],
      sizes: ["34","36","38"],
      images: ["images/aclothes/blue-satin-drape-tank.jpg"],
      description: "Blue Satin Drape Tank · handcrafted tops, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "classic-canvas-sneakers",
      name: "Classic Canvas Sneakers",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Sneakers",
      price: 3480,
      originalPrice: 4640,
      rating: 4.5,
      reviews: 132,
      popularity: 81,
      isNew: true,
      tags: ["sneakers","canvas","everyday"],
      colors: ["White","Black"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8","UK 9","UK 10"],
      images: ["images/aclothes/classic-canvas-sneakers.jpg"],
      description: "Classic Canvas Sneakers · handcrafted sneakers, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "beige-highwaist-trousers",
      name: "The Beige Fit High-Waist Trousers",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Trousers",
      price: 3820,
      originalPrice: null,
      rating: 4.6,
      reviews: 96,
      popularity: 77,
      isNew: true,
      tags: ["wide-leg","high-waist","work"],
      colors: ["Beige"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/beige-highwaist-trousers.jpg"],
      description: "The Beige Fit High-Waist Trousers · handcrafted trousers, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "striped-corset-maxi",
      name: "Striped Halter Corset Maxi Dress",
      brand: "Boho Threads",
      category: "clothing",
      subcategory: "Dresses",
      price: 6560,
      originalPrice: 8640,
      rating: 4.8,
      reviews: 157,
      popularity: 90,
      isNew: true,
      tags: ["halter","corset","maxi"],
      colors: ["White","Black"],
      sizes: ["32","34","36","38"],
      images: ["images/aclothes/striped-corset-maxi.jpg"],
      description: "Striped Halter Corset Maxi Dress · handcrafted dresses, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "embroidered-cushion-cover",
      name: "Blue Formal Pants",
      brand: "Terracotta Tales",
      category: "clothing",
      subcategory: "Trousers",
      price: 2160,
      originalPrice: null,
      rating: 4.4,
      reviews: 45,
      popularity: 53,
      isNew: false,
      tags: ["formal","trousers","blue"],
      colors: ["Blue"],
      sizes: ["26","28","30","32","34"],
      images: ["images/aclothes/embroidered-cushion-cover.jpg"],
      description: "Blue Formal Pants · handcrafted trousers, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "canvas-weekender-tote",
      name: "Formal Striped Pants",
      brand: "Swadeshi Wares",
      category: "clothing",
      subcategory: "Trousers",
      price: 2660,
      originalPrice: null,
      rating: 4.5,
      reviews: 61,
      popularity: 56,
      isNew: true,
      tags: ["formal","striped","trousers"],
      colors: ["Blue","Grey"],
      sizes: ["26","28","30","32","34"],
      images: ["images/aclothes/canvas-weekender-tote.jpg"],
      description: "Formal Striped Pants · handcrafted trousers, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "golden-jhumka-earrings",
      name: "Classic Jean Dress",
      brand: "Atelier Moti",
      category: "clothing",
      subcategory: "Dresses",
      price: 2320,
      originalPrice: null,
      rating: 4.7,
      reviews: 88,
      popularity: 65,
      isNew: false,
      tags: ["denim","dress","classic"],
      colors: ["Denim"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/golden-jhumka-earrings.jpg"],
      description: "Classic Jean Dress · handcrafted dresses, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "printed-chiffon-scarf",
      name: "Printed Summer Dress",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Dresses",
      price: 1500,
      originalPrice: null,
      rating: 4.3,
      reviews: 51,
      popularity: 43,
      isNew: false,
      tags: ["dress","summer","printed"],
      colors: ["Multicolour"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/printed-chiffon-scarf.jpg"],
      description: "Printed Summer Dress · handcrafted dresses, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "macrame-wall-hanging",
      name: "White Co-ord Set",
      brand: "Terracotta Tales",
      category: "clothing",
      subcategory: "Sets",
      price: 2980,
      originalPrice: null,
      rating: 4.6,
      reviews: 34,
      popularity: 40,
      isNew: false,
      tags: ["co-ord","white","cotton"],
      colors: ["White"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/macrame-wall-hanging.jpg"],
      description: "White Co-ord Set · handcrafted sets, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "terracotta-planter-pot",
      name: "Brown Zara Top",
      brand: "Terracotta Tales",
      category: "clothing",
      subcategory: "Tops",
      price: 1740,
      originalPrice: null,
      rating: 4.5,
      reviews: 57,
      popularity: 45,
      isNew: false,
      tags: ["top","brown","casual"],
      colors: ["Brown"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/terracotta-planter-pot.jpg"],
      description: "Brown Zara Top · handcrafted tops, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "paisley-cotton-duffel",
      name: "Jean Co-ord Set",
      brand: "Swadeshi Wares",
      category: "clothing",
      subcategory: "Sets",
      price: 4480,
      originalPrice: 5640,
      rating: 4.6,
      reviews: 48,
      popularity: 61,
      isNew: true,
      tags: ["co-ord","denim","set"],
      colors: ["Denim"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/paisley-cotton-duffel.jpg"],
      description: "Jean Co-ord Set · handcrafted sets, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "brass-leaf-brooch",
      name: "Denim Designer Tie",
      brand: "Atelier Moti",
      category: "accessories",
      subcategory: "Ties",
      price: 1420,
      originalPrice: null,
      rating: 4.5,
      reviews: 42,
      popularity: 38,
      isNew: false,
      tags: ["tie","denim","formal"],
      colors: ["Denim"],
      sizes: ["One Size"],
      images: ["images/aclothes/brass-leaf-brooch.jpg"],
      description: "Denim Designer Tie · handcrafted ties, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "handloom-table-runner",
      name: "Star Bag",
      brand: "Terracotta Tales",
      category: "bags",
      subcategory: "Shoulder",
      price: 2580,
      originalPrice: null,
      rating: 4.4,
      reviews: 26,
      popularity: 36,
      isNew: false,
      tags: ["bag","star","evening"],
      colors: ["Gold","Black"],
      sizes: ["One Size"],
      images: ["images/aclothes/handloom-table-runner.jpg"],
      description: "Star Bag · handcrafted shoulder, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "waxed-canvas-backpack",
      name: "Bedazzled Boots",
      brand: "Swadeshi Wares",
      category: "shoes",
      subcategory: "Boots",
      price: 4820,
      originalPrice: null,
      rating: 4.7,
      reviews: 74,
      popularity: 69,
      isNew: true,
      tags: ["boots","bedazzled","party"],
      colors: ["Silver","Black"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8","UK 9"],
      images: ["images/aclothes/waxed-canvas-backpack.jpg"],
      description: "Bedazzled Boots · handcrafted boots, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "ceramic-coaster-set",
      name: "Indian Print Shoes",
      brand: "Terracotta Tales",
      category: "shoes",
      subcategory: "Flats",
      price: 1160,
      originalPrice: null,
      rating: 4.3,
      reviews: 33,
      popularity: 32,
      isNew: false,
      tags: ["indian-print","flats","ethnic"],
      colors: ["Multicolour"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8"],
      images: ["images/aclothes/ceramic-coaster-set.jpg"],
      description: "Indian Print Shoes · handcrafted flats, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "canvas-travel-backpack",
      name: "Canvas Travel Backpack",
      brand: "Swadeshi Wares",
      category: "bags",
      subcategory: "Backpacks",
      price: 3660,
      originalPrice: 4820,
      rating: 4.6,
      reviews: 58,
      popularity: 62,
      isNew: true,
      tags: ["backpack","canvas","travel"],
      colors: ["Olive","Tan"],
      sizes: ["One Size"],
      images: ["images/aclothes/canvas-travel-backpack.jpg"],
      description: "Canvas Travel Backpack · handcrafted backpacks, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "everyday-leather-tote",
      name: "Everyday Backpack",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Backpacks",
      price: 5640,
      originalPrice: 7300,
      rating: 4.7,
      reviews: 121,
      popularity: 74,
      isNew: true,
      tags: ["backpack","everyday","leather"],
      colors: ["Black","Tan"],
      sizes: ["One Size"],
      images: ["images/aclothes/everyday-leather-tote.jpg"],
      description: "Everyday Backpack · handcrafted backpacks, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "cream-blush-wand",
      name: "Cream Blush Wand",
      brand: "Veridana",
      category: "beauty",
      subcategory: "Makeup",
      price: 2160,
      originalPrice: null,
      rating: 4.5,
      reviews: 96,
      popularity: 70,
      isNew: true,
      tags: ["blush","makeup","clean-beauty"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/cream-blush-wand.jpg"],
      description: "Cream Blush Wand · handcrafted makeup, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "burgundy-buckle-shoulder-bag",
      name: "Burgundy Buckle Shoulder Bag",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Shoulder",
      price: 6140,
      originalPrice: 7960,
      rating: 4.7,
      reviews: 87,
      popularity: 78,
      isNew: true,
      tags: ["shoulder-bag","buckle","evening"],
      colors: ["Burgundy"],
      sizes: ["One Size"],
      images: ["images/aclothes/burgundy-buckle-shoulder-bag.jpg"],
      description: "Burgundy Buckle Shoulder Bag · handcrafted shoulder, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "candle-warmer-lamp",
      name: "Candle Warmer Lamp",
      brand: "Terracotta Tales",
      category: "home",
      subcategory: "Objects",
      price: 4320,
      originalPrice: 5480,
      rating: 4.8,
      reviews: 44,
      popularity: 63,
      isNew: false,
      tags: ["lamp","candle","ambient"],
      colors: ["Gold","Black"],
      sizes: ["One Size"],
      images: ["images/aclothes/candle-warmer-lamp.jpg"],
      description: "Candle Warmer Lamp · handcrafted objects, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "tealight-candle-holder-set",
      name: "Pool Ball Tealight Holder Set",
      brand: "Terracotta Tales",
      category: "home",
      subcategory: "Objects",
      price: 2820,
      originalPrice: null,
      rating: 4.5,
      reviews: 39,
      popularity: 51,
      isNew: false,
      tags: ["tealight","candle-holder","set"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/tealight-candle-holder-set.jpg"],
      description: "Pool Ball Tealight Holder Set · handcrafted objects, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "designer-leather-shoulder-bag",
      name: "Designer Leather Shoulder Bag",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Shoulder",
      price: 10620,
      originalPrice: 13120,
      rating: 4.8,
      reviews: 132,
      popularity: 82,
      isNew: true,
      tags: ["designer","leather","shoulder"],
      colors: ["Black"],
      sizes: ["One Size"],
      images: ["images/aclothes/designer-leather-shoulder-bag.jpg"],
      description: "Designer Leather Shoulder Bag · handcrafted shoulder, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "new-nudes-palette",
      name: "Pro New Nudes Eye Palette",
      brand: "Veridana",
      category: "beauty",
      subcategory: "Makeup",
      price: 3660,
      originalPrice: 4640,
      rating: 4.7,
      reviews: 208,
      popularity: 76,
      isNew: true,
      tags: ["eyeshadow","palette","pro"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/new-nudes-palette.jpg"],
      description: "Pro New Nudes Eye Palette · handcrafted makeup, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "wedding-eye-palette",
      name: "Wedding-Day Eye Palette",
      brand: "Veridana",
      category: "beauty",
      subcategory: "Makeup",
      price: 3160,
      originalPrice: 4060,
      rating: 4.6,
      reviews: 142,
      popularity: 64,
      isNew: false,
      tags: ["eyeshadow","wedding","pastel"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/wedding-eye-palette.jpg"],
      description: "Wedding-Day Eye Palette · handcrafted makeup, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "handloom-midi-skirt",
      name: "Designer Indian-Print Bag",
      brand: "Sirohi",
      category: "bags",
      subcategory: "Handbags",
      price: 2660,
      originalPrice: 3480,
      rating: 4.5,
      reviews: 52,
      popularity: 58,
      isNew: false,
      tags: ["bag","indian-print","designer"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/handloom-midi-skirt.jpg"],
      description: "Designer Indian-Print Bag · handcrafted handbags, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "bloom-print-kurta",
      name: "Sun & Moon Earrings",
      brand: "Boho Threads",
      category: "jewellery",
      subcategory: "Earrings",
      price: 3480,
      originalPrice: 4480,
      rating: 4.6,
      reviews: 74,
      popularity: 66,
      isNew: true,
      tags: ["celestial","earrings","gold"],
      colors: ["Gold","Silver"],
      sizes: ["One Size"],
      images: ["images/aclothes/bloom-print-kurta.jpg"],
      description: "Sun & Moon Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "printed-fleece-hoodie",
      name: "Celestial Bodies Necklace",
      brand: "Artisanal Threads",
      category: "jewellery",
      subcategory: "Necklaces",
      price: 3240,
      originalPrice: 4060,
      rating: 4.4,
      reviews: 46,
      popularity: 47,
      isNew: false,
      tags: ["necklace","celestial","gold"],
      colors: ["Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/printed-fleece-hoodie.jpg"],
      description: "Celestial Bodies Necklace · handcrafted necklaces, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "bandhani-co-ord",
      name: "Bandhani Print Co-ord",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Sets",
      price: 4820,
      originalPrice: 6300,
      rating: 4.7,
      reviews: 83,
      popularity: 72,
      isNew: true,
      tags: ["co-ord","bandhani","silk-touch"],
      colors: ["Red","Yellow"],
      sizes: ["34","36","38","40"],
      images: ["images/aclothes/bandhani-co-ord.jpg"],
      description: "Bandhani Print Co-ord · handcrafted sets, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "leather-crossbody-mini",
      name: "Indian Maxi Skirt",
      brand: "Mirabeau",
      category: "clothing",
      subcategory: "Skirts",
      price: 4320,
      originalPrice: 5480,
      rating: 4.6,
      reviews: 61,
      popularity: 60,
      isNew: false,
      tags: ["maxi-skirt","indian-print","ethnic"],
      colors: ["Multicolour"],
      sizes: ["32","34","36","38","40"],
      images: ["images/aclothes/leather-crossbody-mini.jpg"],
      description: "Indian Maxi Skirt · handcrafted skirts, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "oxidised-jhumka-set",
      name: "Clockwork Heels",
      brand: "Atelier Moti",
      category: "shoes",
      subcategory: "Heels",
      price: 2400,
      originalPrice: 3160,
      rating: 4.7,
      reviews: 92,
      popularity: 68,
      isNew: true,
      tags: ["heels","clockwork","statement"],
      colors: ["Gold","Black"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8"],
      images: ["images/aclothes/oxidised-jhumka-set.jpg"],
      description: "Clockwork Heels · handcrafted heels, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "block-print-cushion-duo",
      name: "Silver Mesh Heels",
      brand: "Terracotta Tales",
      category: "shoes",
      subcategory: "Heels",
      price: 3820,
      originalPrice: 4820,
      rating: 4.6,
      reviews: 37,
      popularity: 42,
      isNew: false,
      tags: ["heels","mesh","party"],
      colors: ["Silver"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8"],
      images: ["images/aclothes/block-print-cushion-duo.jpg"],
      description: "Silver Mesh Heels · handcrafted heels, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "chiffon-dupatta",
      name: "Maroon Fish-Eye Leather Heels",
      brand: "Sirohi",
      category: "shoes",
      subcategory: "Heels",
      price: 2000,
      originalPrice: null,
      rating: 4.4,
      reviews: 43,
      popularity: 45,
      isNew: false,
      tags: ["heels","leather","maroon"],
      colors: ["Maroon"],
      sizes: ["UK 3","UK 4","UK 5","UK 6","UK 7","UK 8"],
      images: ["images/aclothes/chiffon-dupatta.jpg"],
      description: "Maroon Fish-Eye Leather Heels · handcrafted heels, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "embroidered-festive-flats",
      name: "Blush Liquid Tint",
      brand: "Charmpad Studio",
      category: "beauty",
      subcategory: "Makeup",
      price: 3900,
      originalPrice: 4980,
      rating: 4.6,
      reviews: 57,
      popularity: 61,
      isNew: true,
      tags: ["blush","makeup","liquid-tint"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/embroidered-festive-flats.jpg"],
      description: "Blush Liquid Tint · handcrafted makeup, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "satin-quilted-pouch",
      name: "Eyeshadow Palette",
      brand: "Swadeshi Wares",
      category: "beauty",
      subcategory: "Makeup",
      price: 2320,
      originalPrice: null,
      rating: 4.5,
      reviews: 48,
      popularity: 43,
      isNew: false,
      tags: ["eyeshadow","palette","makeup"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/satin-quilted-pouch.jpg"],
      description: "Eyeshadow Palette · handcrafted makeup, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "handpainted-boho-blouse",
      name: "Clay Hand-Painted Earrings",
      brand: "Rangoli Studio",
      category: "jewellery",
      subcategory: "Earrings",
      price: 2980,
      originalPrice: 3820,
      rating: 4.6,
      reviews: 63,
      popularity: 57,
      isNew: true,
      tags: ["clay","earrings","handpainted"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/handpainted-boho-blouse.jpg"],
      description: "Clay Hand-Painted Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "mango-wood-decor",
      name: "Tulip Pearl Earrings",
      brand: "Terracotta Tales",
      category: "jewellery",
      subcategory: "Earrings",
      price: 2580,
      originalPrice: 3320,
      rating: 4.4,
      reviews: 35,
      popularity: 39,
      isNew: false,
      tags: ["pearl","tulip","earrings"],
      colors: ["Pearl"],
      sizes: ["One Size"],
      images: ["images/aclothes/mango-wood-decor.jpg"],
      description: "Tulip Pearl Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "silk-mix-stole",
      name: "Ocean-Scented Candles",
      brand: "Boho Threads",
      category: "home",
      subcategory: "Scent",
      price: 2160,
      originalPrice: 2820,
      rating: 4.5,
      reviews: 56,
      popularity: 49,
      isNew: true,
      tags: ["candle","ocean","home"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/silk-mix-stole.jpg"],
      description: "Ocean-Scented Candles · handcrafted scent, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "slouchy-leather-handbag",
      name: "Slouchy Denim Handbag",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Handbags",
      price: 5140,
      originalPrice: 6640,
      rating: 4.6,
      reviews: 66,
      popularity: 59,
      isNew: false,
      tags: ["handbag","denim","slouchy"],
      colors: ["Denim"],
      sizes: ["One Size"],
      images: ["images/aclothes/slouchy-leather-handbag.jpg"],
      description: "Slouchy Denim Handbag · handcrafted handbags, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "polymer-clay-earrings",
      name: "Polymer Clay Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 1740,
      originalPrice: null,
      rating: 4.7,
      reviews: 89,
      popularity: 65,
      isNew: true,
      tags: ["polymer-clay","handmade","statement"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/polymer-clay-earrings.jpg"],
      description: "Polymer Clay Earrings · handcrafted earrings, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "jules-blazer",
      name: "YSL Lipstick",
      brand: "Estrella",
      category: "beauty",
      subcategory: "Makeup",
      price: 7300,
      originalPrice: 9140,
      rating: 4.7,
      reviews: 54,
      popularity: 55,
      isNew: false,
      tags: ["lipstick","makeup","luxe"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/jules-blazer.jpg"],
      description: "YSL Lipstick · handcrafted makeup, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "lorelai-co-ord",
      name: "Vintage Phone Ring",
      brand: "Boho Threads",
      category: "accessories",
      subcategory: "Phone",
      price: 4480,
      originalPrice: 5820,
      rating: 4.6,
      reviews: 61,
      popularity: 52,
      isNew: false,
      tags: ["phone-ring","vintage","accessory"],
      colors: ["Gold","Silver"],
      sizes: ["One Size"],
      images: ["images/aclothes/lorelai-co-ord.jpg"],
      description: "Vintage Phone Ring · handcrafted phone, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    },
    {
      id: "vintage-lily-lamp",
      name: "Vintage Lily Table Lamp",
      brand: "Terracotta Tales",
      category: "home",
      subcategory: "Lighting",
      price: 5480,
      originalPrice: 6980,
      rating: 4.8,
      reviews: 71,
      popularity: 67,
      isNew: true,
      tags: ["lamp","vintage","lily"],
      colors: ["Gold","Cream"],
      sizes: ["One Size"],
      images: ["images/aclothes/vintage-lily-lamp.jpg"],
      description: "Vintage Lily Table Lamp · handcrafted lighting, chosen by Bloom for how well it wears and how much character it carries. Small-batch and one-of-one, so when it is gone, it is truly gone."
    }
  ];

  const CATEGORY_META = {
    clothing:     { name: 'Clothing',     icon: 'dress', tagline: 'Wearable blooms', weight: 1 },
    shoes:        { name: 'Shoes',        icon: 'shoe', tagline: 'Well-heeled garden walks', weight: 2 },
    bags:         { name: 'Bags',         icon: 'bag', tagline: 'Carry the season', weight: 3 },
    jewellery:    { name: 'Jewellery',    icon: 'ring', tagline: 'Botanical gold', weight: 4 },
    beauty:       { name: 'Beauty',       icon: 'flower', tagline: 'Petals for skin', weight: 5 },
    home:         { name: 'Home',         icon: 'home', tagline: 'Grow a softer home', weight: 6 },
    accessories:  { name: 'Accessories',  icon: 'glasses', tagline: 'Finishing touches', weight: 7 }
  };

  /* materialise the discount field (per requirement) */
  PRODUCTS.forEach(p => {
    p.discount = p.originalPrice ? Math.round((1 - p.price / p.originalPrice) * 100) : 0;
  });

  window.CATEGORY_META = CATEGORY_META;
  window.COUPONS = {
    FLEUR10:  { kind: 'percent', value: 10, label: '10% off · FLEUR10' },
    BLOOM15:  { kind: 'percent', value: 15, minSpend: 4999, label: '15% off · BLOOM15' },
    PETAL20:  { kind: 'percent', value: 20, minSpend: 9999, label: '20% off · PETAL20' },
    FREESHIP: { kind: 'shipping', value: 0, label: 'Free delivery · FREESHIP' }
  };

  window.PRODUCTS = PRODUCTS;

  window.getProduct = function (id) {
    return PRODUCTS.find(function (p) { return p.id === id; }) || null;
  };

  window.relatedProducts = function (product, count) {
    var list = PRODUCTS.filter(function (p) {
      return p.id !== product.id && p.category === product.category;
    });
    if (list.length < count) {
      list = list.concat(PRODUCTS.filter(function (p) {
        return list.indexOf(p) === -1 && p.id !== product.id;
      }));
    }
    return list.slice(0, count);
  };
})();
