/* ============================================================
   Bloom · Product dataset (auto-generated from images/aclothes)
   Regenerate with: node scripts/build-catalog.js
   ============================================================ */

;(function () {
  'use strict';

  const PRODUCTS = [
    {
      id: "maryjanes-burgundy",
      name: "Burgundy Patent Slingback Mary Janes",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Heels",
      price: 950,
      condition: "Good",
      listedDaysAgo: 4,
      seller: { name: "Aditi Rao", username: "aditi.r", email: "aditi.r@ashoka.edu.in", rating: 4.9, sales: 31, responseRate: 98, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 64,
      popularity: 78,
      isNew: true,
      tags: ["vintage","patent","kitten-heel"],
      colors: ["Burgundy"],
      sizes: ["UK 7"],
      images: ["images/aclothes/maryjanes-burgundy.jpg"],
      description: "Burgundy Patent Slingback Mary Janes · Good condition · listed by Aditi Rao (aditi.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "alibox-gift-bundle",
      name: "Embroidered Black Lace Shoes",
      brand: "Swadeshi Wares",
      category: "shoes",
      subcategory: "Flats",
      price: 750,
      condition: "Like New",
      listedDaysAgo: 12,
      seller: { name: "Ananya Iyer", username: "ananya.i", email: "ananya.i@ashoka.edu.in", rating: 4.8, sales: 12, responseRate: 95, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 41,
      popularity: 44,
      isNew: false,
      tags: ["embroidered","lace","black"],
      colors: ["Black"],
      sizes: ["UK 3"],
      images: ["images/aclothes/alibox-gift-bundle.jpg"],
      description: "Embroidered Black Lace Shoes · Like New condition · listed by Ananya Iyer (ananya.i). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "vangogh-sunflower-earrings",
      name: "Van Gogh Sunflower Earrings",
      brand: "Atelier Moti",
      category: "jewellery",
      subcategory: "Earrings",
      price: 600,
      condition: "Excellent",
      listedDaysAgo: 9,
      seller: { name: "Rhea Kapoor", username: "rhea.k", email: "rhea.k@ashoka.edu.in", rating: 4.7, sales: 19, responseRate: 90, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.8,
      reviews: 87,
      popularity: 81,
      isNew: true,
      tags: ["hand-painted","art","statement"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/vangogh-sunflower-earrings.jpg"],
      description: "Van Gogh Sunflower Earrings · Excellent condition · listed by Rhea Kapoor (rhea.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "bleach-tank-top",
      name: "Bleach Design Tank Top",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Tops",
      price: 600,
      condition: "Fair",
      listedDaysAgo: 23,
      seller: { name: "Diya Menon", username: "diya.m", email: "diya.m@ashoka.edu.in", rating: 5, sales: 8, responseRate: 100, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 52,
      popularity: 66,
      isNew: false,
      tags: ["bleach","summer","streetwear"],
      colors: ["White"],
      sizes: ["38"],
      images: ["images/aclothes/bleach-tank-top.jpg"],
      description: "Bleach Design Tank Top · Fair condition · listed by Diya Menon (diya.m). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "comfort-cream-crop-tee",
      name: "Block-Printed Cream Crop Tee",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Tops",
      price: 450,
      condition: "Excellent",
      listedDaysAgo: 20,
      seller: { name: "Ishaan Verma", username: "ishaan.v", email: "ishaan.v@ashoka.edu.in", rating: 4.6, sales: 24, responseRate: 88, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 128,
      popularity: 74,
      isNew: true,
      tags: ["block-print","cotton","crop"],
      colors: ["Cream"],
      sizes: ["38"],
      images: ["images/aclothes/comfort-cream-crop-tee.jpg"],
      description: "Block-Printed Cream Crop Tee · Excellent condition · listed by Ishaan Verma (ishaan.v). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "kolhapuri-sandals",
      name: "Earthy Kolhapuri Sandals",
      brand: "Kolhapur Collective",
      category: "shoes",
      subcategory: "Sandals",
      price: 750,
      condition: "Excellent",
      listedDaysAgo: 15,
      seller: { name: "Kabir Shah", username: "kabir.s", email: "kabir.s@ashoka.edu.in", rating: 4.4, sales: 15, responseRate: 82, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.9,
      reviews: 302,
      popularity: 93,
      isNew: true,
      tags: ["handmade","leather","traditional"],
      colors: ["Maroon"],
      sizes: ["UK 8"],
      images: ["images/aclothes/kolhapuri-sandals.jpg"],
      description: "Earthy Kolhapuri Sandals · Excellent condition · listed by Kabir Shah (kabir.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "green-quilling-jhumka",
      name: "Green Quilled Jhumka Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 600,
      condition: "Like New",
      listedDaysAgo: 19,
      seller: { name: "Meera Nair", username: "meera.n", email: "meera.n@ashoka.edu.in", rating: 4.9, sales: 27, responseRate: 97, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 118,
      popularity: 88,
      isNew: false,
      tags: ["quilling","jhumka","paper-art"],
      colors: ["Green"],
      sizes: ["One Size"],
      images: ["images/aclothes/green-quilling-jhumka.jpg"],
      description: "Green Quilled Jhumka Earrings · Like New condition · listed by Meera Nair (meera.n). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "guitar-bleach-tank",
      name: "Hand-Bleached Guitar Tank",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Tops",
      price: 300,
      condition: "Excellent",
      listedDaysAgo: 2,
      seller: { name: "Nikhil Bose", username: "nikhil.b", email: "nikhil.b@ashoka.edu.in", rating: 4.3, sales: 6, responseRate: 78, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.3,
      reviews: 37,
      popularity: 52,
      isNew: false,
      tags: ["bleach","streetwear","graphic"],
      colors: ["Black"],
      sizes: ["38"],
      images: ["images/aclothes/guitar-bleach-tank.jpg"],
      description: "Hand-Bleached Guitar Tank · Excellent condition · listed by Nikhil Bose (nikhil.b). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "dragonfly-arm-cuff",
      name: "Handmade Dragonfly Arm Cuff",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Cuffs",
      price: 400,
      condition: "Excellent",
      listedDaysAgo: 15,
      seller: { name: "Aisha Khan", username: "aisha.k", email: "aisha.k@ashoka.edu.in", rating: 4.8, sales: 22, responseRate: 93, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 93,
      popularity: 70,
      isNew: true,
      tags: ["wire-wrap","handmade","boho"],
      colors: ["Antique Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/dragonfly-arm-cuff.jpg"],
      description: "Handmade Dragonfly Arm Cuff · Excellent condition · listed by Aisha Khan (aisha.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "handpainted-wide-jeans",
      name: "Hand-Painted Wide Denim Jeans",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 850,
      condition: "Like New",
      listedDaysAgo: 13,
      seller: { name: "Rohit Desai", username: "rohit.d", email: "rohit.d@ashoka.edu.in", rating: 4.5, sales: 11, responseRate: 85, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 49,
      popularity: 68,
      isNew: true,
      tags: ["hand-painted","denim","one-of-one"],
      colors: ["Indigo"],
      sizes: ["38"],
      images: ["images/aclothes/handpainted-wide-jeans.jpg"],
      description: "Hand-Painted Wide Denim Jeans · Like New condition · listed by Rohit Desai (rohit.d). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "moon-sun-jeans",
      name: "Moon & Sun Painted Jeans",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 500,
      condition: "Excellent",
      listedDaysAgo: 21,
      seller: { name: "Sanya Gupta", username: "sanya.g", email: "sanya.g@ashoka.edu.in", rating: 4.7, sales: 16, responseRate: 91, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.8,
      reviews: 143,
      popularity: 91,
      isNew: false,
      tags: ["painted","celestial","denim"],
      colors: ["Washed Blue"],
      sizes: ["36"],
      images: ["images/aclothes/moon-sun-jeans.jpg"],
      description: "Moon & Sun Painted Jeans · Excellent condition · listed by Sanya Gupta (sanya.g). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "cherry-earrings",
      name: "Quilled Cherry Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 350,
      condition: "Like New",
      listedDaysAgo: 24,
      seller: { name: "Vivaan Joshi", username: "vivaan.j", email: "vivaan.j@ashoka.edu.in", rating: 4.2, sales: 4, responseRate: 74, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 77,
      popularity: 59,
      isNew: false,
      tags: ["quilling","fruit","playful"],
      colors: ["Red"],
      sizes: ["One Size"],
      images: ["images/aclothes/cherry-earrings.jpg"],
      description: "Quilled Cherry Earrings · Like New condition · listed by Vivaan Joshi (vivaan.j). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "spiral-pendant-necklace",
      name: "Spiral Swirl Pendant Necklace",
      brand: "Estrella",
      category: "jewellery",
      subcategory: "Necklaces",
      price: 450,
      condition: "Excellent",
      listedDaysAgo: 26,
      seller: { name: "Tara Pillai", username: "tara.p", email: "tara.p@ashoka.edu.in", rating: 4.9, sales: 35, responseRate: 99, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 88,
      popularity: 75,
      isNew: true,
      tags: ["minimal","silver","unisex"],
      colors: ["Silver"],
      sizes: ["One Size"],
      images: ["images/aclothes/spiral-pendant-necklace.jpg"],
      description: "Spiral Swirl Pendant Necklace · Excellent condition · listed by Tara Pillai (tara.p). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "bohemian-linen-dress",
      name: "Bohemian Pure Linen Shirt",
      brand: "Boho Threads",
      category: "clothing",
      subcategory: "Shirts",
      price: 750,
      condition: "Fair",
      listedDaysAgo: 11,
      seller: { name: "Arjun Reddy", username: "arjun.r", email: "arjun.r@ashoka.edu.in", rating: 4.6, sales: 18, responseRate: 87, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.8,
      reviews: 176,
      popularity: 89,
      isNew: true,
      tags: ["linen","shirt","handmade"],
      colors: ["Green"],
      sizes: ["34"],
      images: ["images/aclothes/bohemian-linen-dress.jpg"],
      description: "Bohemian Pure Linen Shirt · Fair condition · listed by Arjun Reddy (arjun.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "collectors-ceramic-vessel",
      name: "Ceramic Earrings",
      brand: "Terracotta Tales",
      category: "jewellery",
      subcategory: "Earrings",
      price: 400,
      condition: "Like New",
      listedDaysAgo: 25,
      seller: { name: "Zoya Sheikh", username: "zoya.s", email: "zoya.s@ashoka.edu.in", rating: 4.8, sales: 13, responseRate: 94, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 61,
      popularity: 47,
      isNew: false,
      tags: ["ceramic","earrings","handmade"],
      colors: ["Cream"],
      sizes: ["One Size"],
      images: ["images/aclothes/collectors-ceramic-vessel.jpg"],
      description: "Ceramic Earrings · Like New condition · listed by Zoya Sheikh (zoya.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "tiger-eye-shirt",
      name: "Tiger Eye Statement Shirt",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Shirts",
      price: 650,
      condition: "Excellent",
      listedDaysAgo: 9,
      seller: { name: "Dev Malhotra", username: "dev.m", email: "dev.m@ashoka.edu.in", rating: 4.4, sales: 9, responseRate: 80, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 94,
      popularity: 79,
      isNew: true,
      tags: ["printed","oversized","statement"],
      colors: ["Multicolour"],
      sizes: ["34"],
      images: ["images/aclothes/tiger-eye-shirt.jpg"],
      description: "Tiger Eye Statement Shirt · Excellent condition · listed by Dev Malhotra (dev.m). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "tiger-graphic-tee",
      name: "Tiger Graphic Tee",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Tees",
      price: 900,
      condition: "Excellent",
      listedDaysAgo: 14,
      seller: { name: "Kavya Rao", username: "kavya.r", email: "kavya.r@ashoka.edu.in", rating: 4.7, sales: 21, responseRate: 92, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 58,
      popularity: 63,
      isNew: false,
      tags: ["graphic","streetwear"],
      colors: ["Black"],
      sizes: ["38"],
      images: ["images/aclothes/tiger-graphic-tee.jpg"],
      description: "Tiger Graphic Tee · Excellent condition · listed by Kavya Rao (kavya.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "bleach-streetwear-tee",
      name: "Trendy Bleach Crop Top",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Tops",
      price: 700,
      condition: "Good",
      listedDaysAgo: 10,
      seller: { name: "Yash Patel", username: "yash.p", email: "yash.p@ashoka.edu.in", rating: 4.3, sales: 7, responseRate: 76, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.3,
      reviews: 41,
      popularity: 51,
      isNew: false,
      tags: ["bleach","crop","streetwear"],
      colors: ["Black"],
      sizes: ["32"],
      images: ["images/aclothes/bleach-streetwear-tee.jpg"],
      description: "Trendy Bleach Crop Top · Good condition · listed by Yash Patel (yash.p). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "embroidered-slip-dress",
      name: "Wire Earrings",
      brand: "Estrella",
      category: "jewellery",
      subcategory: "Earrings",
      price: 150,
      condition: "Excellent",
      listedDaysAgo: 20,
      seller: { name: "Mira Sen", username: "mira.s", email: "mira.s@ashoka.edu.in", rating: 4.9, sales: 29, responseRate: 96, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 66,
      popularity: 72,
      isNew: false,
      tags: ["wire","earrings","minimal"],
      colors: ["Silver"],
      sizes: ["One Size"],
      images: ["images/aclothes/embroidered-slip-dress.jpg"],
      description: "Wire Earrings · Excellent condition · listed by Mira Sen (mira.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "chanderi-co-ord",
      name: "Spiderman Sneakers",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Sneakers",
      price: 1150,
      condition: "Like New",
      listedDaysAgo: 12,
      seller: { name: "Neel Bhatia", username: "neel.b", email: "neel.b@ashoka.edu.in", rating: 4.5, sales: 14, responseRate: 84, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 121,
      popularity: 84,
      isNew: true,
      tags: ["sneakers","graphic","streetwear"],
      colors: ["Black"],
      sizes: ["UK 9"],
      images: ["images/aclothes/chanderi-co-ord.jpg"],
      description: "Spiderman Sneakers · Like New condition · listed by Neel Bhatia (neel.b). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "handloom-silk-saree",
      name: "Clay Earrings",
      brand: "Atelier Moti",
      category: "jewellery",
      subcategory: "Earrings",
      price: 250,
      condition: "Excellent",
      listedDaysAgo: 2,
      seller: { name: "Ananya Gokhale", username: "ananya.g", email: "ananya.g@ashoka.edu.in", rating: 4.8, sales: 17, responseRate: 93, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 98,
      popularity: 87,
      isNew: false,
      tags: ["clay","earrings","handmade"],
      colors: ["Terracotta"],
      sizes: ["One Size"],
      images: ["images/aclothes/handloom-silk-saree.jpg"],
      description: "Clay Earrings · Excellent condition · listed by Ananya Gokhale (ananya.g). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "ankle-strap-flats",
      name: "Embroidered Ankle-Strap Boots",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Boots",
      price: 550,
      condition: "Excellent",
      listedDaysAgo: 26,
      seller: { name: "Riya Chatterjee", username: "riya.c", email: "riya.c@ashoka.edu.in", rating: 4.6, sales: 10, responseRate: 89, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 54,
      popularity: 60,
      isNew: true,
      tags: ["boots","embroidered","ankle"],
      colors: ["Black"],
      sizes: ["UK 5"],
      images: ["images/aclothes/ankle-strap-flats.jpg"],
      description: "Embroidered Ankle-Strap Boots · Excellent condition · listed by Riya Chatterjee (riya.c). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "indigo-block-print-dress",
      name: "Indigo Block-Print Shirt",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Shirts",
      price: 550,
      condition: "Like New",
      listedDaysAgo: 7,
      seller: { name: "Aditi Rao", username: "aditi.r", email: "aditi.r@ashoka.edu.in", rating: 4.9, sales: 31, responseRate: 98, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 88,
      popularity: 76,
      isNew: false,
      tags: ["block-print","shirt","indigo"],
      colors: ["Indigo"],
      sizes: ["36"],
      images: ["images/aclothes/indigo-block-print-dress.jpg"],
      description: "Indigo Block-Print Shirt · Like New condition · listed by Aditi Rao (aditi.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "satin-slip-dress",
      name: "Hand-Painted Dystopian T-Shirt",
      brand: "Estrella",
      category: "clothing",
      subcategory: "Tees",
      price: 450,
      condition: "Fair",
      listedDaysAgo: 5,
      seller: { name: "Ananya Iyer", username: "ananya.i", email: "ananya.i@ashoka.edu.in", rating: 4.8, sales: 12, responseRate: 95, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 73,
      popularity: 71,
      isNew: true,
      tags: ["hand-painted","graphic","tee"],
      colors: ["Multicolour"],
      sizes: ["32"],
      images: ["images/aclothes/satin-slip-dress.jpg"],
      description: "Hand-Painted Dystopian T-Shirt · Fair condition · listed by Ananya Iyer (ananya.i). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "co-ord-lounge-set",
      name: "Cotton Lounge Shirt",
      brand: "IndiMade",
      category: "clothing",
      subcategory: "Shirts",
      price: 700,
      condition: "Like New",
      listedDaysAgo: 25,
      seller: { name: "Rhea Kapoor", username: "rhea.k", email: "rhea.k@ashoka.edu.in", rating: 4.7, sales: 19, responseRate: 90, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 82,
      popularity: 55,
      isNew: false,
      tags: ["lounge","shirt","cotton"],
      colors: ["Cream"],
      sizes: ["32"],
      images: ["images/aclothes/co-ord-lounge-set.jpg"],
      description: "Cotton Lounge Shirt · Like New condition · listed by Rhea Kapoor (rhea.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "printed-midi-skirt",
      name: "Block-Printed Jeans",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 450,
      condition: "Fair",
      listedDaysAgo: 5,
      seller: { name: "Diya Menon", username: "diya.m", email: "diya.m@ashoka.edu.in", rating: 5, sales: 8, responseRate: 100, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 47,
      popularity: 67,
      isNew: false,
      tags: ["block-print","jeans","denim"],
      colors: ["Indigo"],
      sizes: ["26"],
      images: ["images/aclothes/printed-midi-skirt.jpg"],
      description: "Block-Printed Jeans · Fair condition · listed by Diya Menon (diya.m). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "chunky-bead-bracelet",
      name: "Sunflower-Pattern Denim Jeans",
      brand: "Kala Kendra",
      category: "clothing",
      subcategory: "Jeans",
      price: 700,
      condition: "Like New",
      listedDaysAgo: 25,
      seller: { name: "Ishaan Verma", username: "ishaan.v", email: "ishaan.v@ashoka.edu.in", rating: 4.6, sales: 24, responseRate: 88, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 39,
      popularity: 49,
      isNew: false,
      tags: ["sunflower","jeans","denim"],
      colors: ["Blue"],
      sizes: ["26"],
      images: ["images/aclothes/chunky-bead-bracelet.jpg"],
      description: "Sunflower-Pattern Denim Jeans · Like New condition · listed by Ishaan Verma (ishaan.v). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "knotted-silk-band",
      name: "Dragonfly Earrings",
      brand: "Swadeshi Wares",
      category: "jewellery",
      subcategory: "Earrings",
      price: 250,
      condition: "Good",
      listedDaysAgo: 22,
      seller: { name: "Kabir Shah", username: "kabir.s", email: "kabir.s@ashoka.edu.in", rating: 4.4, sales: 15, responseRate: 82, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 72,
      popularity: 57,
      isNew: true,
      tags: ["dragonfly","earrings","boho"],
      colors: ["Antique Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/knotted-silk-band.jpg"],
      description: "Dragonfly Earrings · Good condition · listed by Kabir Shah (kabir.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "matte-hoop-earrings",
      name: "Hand-Painted Sneakers",
      brand: "Estrella",
      category: "shoes",
      subcategory: "Sneakers",
      price: 400,
      condition: "Excellent",
      listedDaysAgo: 27,
      seller: { name: "Meera Nair", username: "meera.n", email: "meera.n@ashoka.edu.in", rating: 4.9, sales: 27, responseRate: 97, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 91,
      popularity: 62,
      isNew: false,
      tags: ["sneakers","hand-painted","custom"],
      colors: ["Multicolour"],
      sizes: ["UK 6"],
      images: ["images/aclothes/matte-hoop-earrings.jpg"],
      description: "Hand-Painted Sneakers · Excellent condition · listed by Meera Nair (meera.n). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "beaded-flower-earrings",
      name: "Beaded Flower Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 450,
      condition: "Good",
      listedDaysAgo: 16,
      seller: { name: "Nikhil Bose", username: "nikhil.b", email: "nikhil.b@ashoka.edu.in", rating: 4.3, sales: 6, responseRate: 78, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 104,
      popularity: 85,
      isNew: true,
      tags: ["floral","beaded","handmade"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/beaded-flower-earrings.jpg"],
      description: "Beaded Flower Earrings · Good condition · listed by Nikhil Bose (nikhil.b). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "spiderman-custom-tee",
      name: "Custom Spider Jeans",
      brand: "Artisanal Threads",
      category: "clothing",
      subcategory: "Jeans",
      price: 450,
      condition: "Fair",
      listedDaysAgo: 5,
      seller: { name: "Aisha Khan", username: "aisha.k", email: "aisha.k@ashoka.edu.in", rating: 4.8, sales: 22, responseRate: 93, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.2,
      reviews: 44,
      popularity: 48,
      isNew: false,
      tags: ["custom","jeans","graphic"],
      colors: ["Indigo"],
      sizes: ["26"],
      images: ["images/aclothes/spiderman-custom-tee.jpg"],
      description: "Custom Spider Jeans · Fair condition · listed by Aisha Khan (aisha.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "diy-painted-jorts",
      name: "DIY Painted Denim Jorts",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Jeans",
      price: 750,
      condition: "Excellent",
      listedDaysAgo: 26,
      seller: { name: "Rohit Desai", username: "rohit.d", email: "rohit.d@ashoka.edu.in", rating: 4.5, sales: 11, responseRate: 85, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 58,
      popularity: 58,
      isNew: true,
      tags: ["painted","jorts","summer"],
      colors: ["Indigo"],
      sizes: ["38"],
      images: ["images/aclothes/diy-painted-jorts.jpg"],
      description: "DIY Painted Denim Jorts · Excellent condition · listed by Rohit Desai (rohit.d). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "bafta-embroidered-top",
      name: "Dual-Color Handbag",
      brand: "IndiMade",
      category: "bags",
      subcategory: "Handbags",
      price: 550,
      condition: "Good",
      listedDaysAgo: 28,
      seller: { name: "Sanya Gupta", username: "sanya.g", email: "sanya.g@ashoka.edu.in", rating: 4.7, sales: 16, responseRate: 91, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 37,
      popularity: 50,
      isNew: false,
      tags: ["handbag","dual-tone","everyday"],
      colors: ["Black"],
      sizes: ["One Size"],
      images: ["images/aclothes/bafta-embroidered-top.jpg"],
      description: "Dual-Color Handbag · Good condition · listed by Sanya Gupta (sanya.g). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "blue-satin-drape-tank",
      name: "Blue Satin Drape Tank",
      brand: "Estrella",
      category: "clothing",
      subcategory: "Tops",
      price: 350,
      condition: "Excellent",
      listedDaysAgo: 3,
      seller: { name: "Vivaan Joshi", username: "vivaan.j", email: "vivaan.j@ashoka.edu.in", rating: 4.2, sales: 4, responseRate: 74, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 69,
      popularity: 73,
      isNew: true,
      tags: ["satin","drape","going-out"],
      colors: ["Cobalt"],
      sizes: ["34"],
      images: ["images/aclothes/blue-satin-drape-tank.jpg"],
      description: "Blue Satin Drape Tank · Excellent condition · listed by Vivaan Joshi (vivaan.j). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "classic-canvas-sneakers",
      name: "Classic Canvas Sneakers",
      brand: "Charmpad Studio",
      category: "shoes",
      subcategory: "Sneakers",
      price: 1000,
      condition: "Excellent",
      listedDaysAgo: 15,
      seller: { name: "Tara Pillai", username: "tara.p", email: "tara.p@ashoka.edu.in", rating: 4.9, sales: 35, responseRate: 99, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 132,
      popularity: 81,
      isNew: true,
      tags: ["sneakers","canvas","everyday"],
      colors: ["Black"],
      sizes: ["UK 10"],
      images: ["images/aclothes/classic-canvas-sneakers.jpg"],
      description: "Classic Canvas Sneakers · Excellent condition · listed by Tara Pillai (tara.p). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "beige-highwaist-trousers",
      name: "The Beige Fit High-Waist Trousers",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Trousers",
      price: 300,
      condition: "Excellent",
      listedDaysAgo: 2,
      seller: { name: "Arjun Reddy", username: "arjun.r", email: "arjun.r@ashoka.edu.in", rating: 4.6, sales: 18, responseRate: 87, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 96,
      popularity: 77,
      isNew: true,
      tags: ["wide-leg","high-waist","work"],
      colors: ["Beige"],
      sizes: ["36"],
      images: ["images/aclothes/beige-highwaist-trousers.jpg"],
      description: "The Beige Fit High-Waist Trousers · Excellent condition · listed by Arjun Reddy (arjun.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "striped-corset-maxi",
      name: "Striped Halter Corset Maxi Dress",
      brand: "Boho Threads",
      category: "clothing",
      subcategory: "Dresses",
      price: 300,
      condition: "Fair",
      listedDaysAgo: 17,
      seller: { name: "Zoya Sheikh", username: "zoya.s", email: "zoya.s@ashoka.edu.in", rating: 4.8, sales: 13, responseRate: 94, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.8,
      reviews: 157,
      popularity: 90,
      isNew: true,
      tags: ["halter","corset","maxi"],
      colors: ["Black"],
      sizes: ["38"],
      images: ["images/aclothes/striped-corset-maxi.jpg"],
      description: "Striped Halter Corset Maxi Dress · Fair condition · listed by Zoya Sheikh (zoya.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "embroidered-cushion-cover",
      name: "Blue Formal Pants",
      brand: "Terracotta Tales",
      category: "clothing",
      subcategory: "Trousers",
      price: 550,
      condition: "Like New",
      listedDaysAgo: 7,
      seller: { name: "Dev Malhotra", username: "dev.m", email: "dev.m@ashoka.edu.in", rating: 4.4, sales: 9, responseRate: 80, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 45,
      popularity: 53,
      isNew: false,
      tags: ["formal","trousers","blue"],
      colors: ["Blue"],
      sizes: ["30"],
      images: ["images/aclothes/embroidered-cushion-cover.jpg"],
      description: "Blue Formal Pants · Like New condition · listed by Dev Malhotra (dev.m). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "canvas-weekender-tote",
      name: "Formal Striped Pants",
      brand: "Swadeshi Wares",
      category: "clothing",
      subcategory: "Trousers",
      price: 800,
      condition: "Excellent",
      listedDaysAgo: 27,
      seller: { name: "Kavya Rao", username: "kavya.r", email: "kavya.r@ashoka.edu.in", rating: 4.7, sales: 21, responseRate: 92, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 61,
      popularity: 56,
      isNew: true,
      tags: ["formal","striped","trousers"],
      colors: ["Grey"],
      sizes: ["30"],
      images: ["images/aclothes/canvas-weekender-tote.jpg"],
      description: "Formal Striped Pants · Excellent condition · listed by Kavya Rao (kavya.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "golden-jhumka-earrings",
      name: "Classic Jean Dress",
      brand: "Atelier Moti",
      category: "clothing",
      subcategory: "Dresses",
      price: 300,
      condition: "Fair",
      listedDaysAgo: 17,
      seller: { name: "Yash Patel", username: "yash.p", email: "yash.p@ashoka.edu.in", rating: 4.3, sales: 7, responseRate: 76, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 88,
      popularity: 65,
      isNew: false,
      tags: ["denim","dress","classic"],
      colors: ["Denim"],
      sizes: ["36"],
      images: ["images/aclothes/golden-jhumka-earrings.jpg"],
      description: "Classic Jean Dress · Fair condition · listed by Yash Patel (yash.p). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "printed-chiffon-scarf",
      name: "Printed Summer Dress",
      brand: "Sirohi",
      category: "clothing",
      subcategory: "Dresses",
      price: 900,
      condition: "Fair",
      listedDaysAgo: 29,
      seller: { name: "Mira Sen", username: "mira.s", email: "mira.s@ashoka.edu.in", rating: 4.9, sales: 29, responseRate: 96, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.3,
      reviews: 51,
      popularity: 43,
      isNew: false,
      tags: ["dress","summer","printed"],
      colors: ["Multicolour"],
      sizes: ["40"],
      images: ["images/aclothes/printed-chiffon-scarf.jpg"],
      description: "Printed Summer Dress · Fair condition · listed by Mira Sen (mira.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "macrame-wall-hanging",
      name: "White Co-ord Set",
      brand: "Terracotta Tales",
      category: "clothing",
      subcategory: "Sets",
      price: 800,
      condition: "Excellent",
      listedDaysAgo: 27,
      seller: { name: "Neel Bhatia", username: "neel.b", email: "neel.b@ashoka.edu.in", rating: 4.5, sales: 14, responseRate: 84, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 34,
      popularity: 40,
      isNew: false,
      tags: ["co-ord","white","cotton"],
      colors: ["White"],
      sizes: ["36"],
      images: ["images/aclothes/macrame-wall-hanging.jpg"],
      description: "White Co-ord Set · Excellent condition · listed by Neel Bhatia (neel.b). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "terracotta-planter-pot",
      name: "Brown Zara Top",
      brand: "Terracotta Tales",
      category: "clothing",
      subcategory: "Tops",
      price: 450,
      condition: "Fair",
      listedDaysAgo: 5,
      seller: { name: "Ananya Gokhale", username: "ananya.g", email: "ananya.g@ashoka.edu.in", rating: 4.8, sales: 17, responseRate: 93, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 57,
      popularity: 45,
      isNew: false,
      tags: ["top","brown","casual"],
      colors: ["Brown"],
      sizes: ["32"],
      images: ["images/aclothes/terracotta-planter-pot.jpg"],
      description: "Brown Zara Top · Fair condition · listed by Ananya Gokhale (ananya.g). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "paisley-cotton-duffel",
      name: "Jean Co-ord Set",
      brand: "Swadeshi Wares",
      category: "clothing",
      subcategory: "Sets",
      price: 900,
      condition: "Fair",
      listedDaysAgo: 29,
      seller: { name: "Riya Chatterjee", username: "riya.c", email: "riya.c@ashoka.edu.in", rating: 4.6, sales: 10, responseRate: 89, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 48,
      popularity: 61,
      isNew: true,
      tags: ["co-ord","denim","set"],
      colors: ["Denim"],
      sizes: ["40"],
      images: ["images/aclothes/paisley-cotton-duffel.jpg"],
      description: "Jean Co-ord Set · Fair condition · listed by Riya Chatterjee (riya.c). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "brass-leaf-brooch",
      name: "Denim Designer Tie",
      brand: "Atelier Moti",
      category: "accessories",
      subcategory: "Ties",
      price: 500,
      condition: "Excellent",
      listedDaysAgo: 27,
      seller: { name: "Aditi Rao", username: "aditi.r", email: "aditi.r@ashoka.edu.in", rating: 4.9, sales: 31, responseRate: 98, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 42,
      popularity: 38,
      isNew: false,
      tags: ["tie","denim","formal"],
      colors: ["Denim"],
      sizes: ["One Size"],
      images: ["images/aclothes/brass-leaf-brooch.jpg"],
      description: "Denim Designer Tie · Excellent condition · listed by Aditi Rao (aditi.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "handloom-table-runner",
      name: "Star Bag",
      brand: "Terracotta Tales",
      category: "bags",
      subcategory: "Shoulder",
      price: 600,
      condition: "Like New",
      listedDaysAgo: 13,
      seller: { name: "Ananya Iyer", username: "ananya.i", email: "ananya.i@ashoka.edu.in", rating: 4.8, sales: 12, responseRate: 95, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 26,
      popularity: 36,
      isNew: false,
      tags: ["bag","star","evening"],
      colors: ["Black"],
      sizes: ["One Size"],
      images: ["images/aclothes/handloom-table-runner.jpg"],
      description: "Star Bag · Like New condition · listed by Ananya Iyer (ananya.i). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "waxed-canvas-backpack",
      name: "Bedazzled Boots",
      brand: "Swadeshi Wares",
      category: "shoes",
      subcategory: "Boots",
      price: 600,
      condition: "Good",
      listedDaysAgo: 22,
      seller: { name: "Rhea Kapoor", username: "rhea.k", email: "rhea.k@ashoka.edu.in", rating: 4.7, sales: 19, responseRate: 90, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 74,
      popularity: 69,
      isNew: true,
      tags: ["boots","bedazzled","party"],
      colors: ["Silver"],
      sizes: ["UK 9"],
      images: ["images/aclothes/waxed-canvas-backpack.jpg"],
      description: "Bedazzled Boots · Good condition · listed by Rhea Kapoor (rhea.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "ceramic-coaster-set",
      name: "Indian Print Shoes",
      brand: "Terracotta Tales",
      category: "shoes",
      subcategory: "Flats",
      price: 1100,
      condition: "Excellent",
      listedDaysAgo: 8,
      seller: { name: "Diya Menon", username: "diya.m", email: "diya.m@ashoka.edu.in", rating: 5, sales: 8, responseRate: 100, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.3,
      reviews: 33,
      popularity: 32,
      isNew: false,
      tags: ["indian-print","flats","ethnic"],
      colors: ["Multicolour"],
      sizes: ["UK 5"],
      images: ["images/aclothes/ceramic-coaster-set.jpg"],
      description: "Indian Print Shoes · Excellent condition · listed by Diya Menon (diya.m). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "canvas-travel-backpack",
      name: "Canvas Travel Backpack",
      brand: "Swadeshi Wares",
      category: "bags",
      subcategory: "Backpacks",
      price: 400,
      condition: "Like New",
      listedDaysAgo: 13,
      seller: { name: "Ishaan Verma", username: "ishaan.v", email: "ishaan.v@ashoka.edu.in", rating: 4.6, sales: 24, responseRate: 88, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 58,
      popularity: 62,
      isNew: true,
      tags: ["backpack","canvas","travel"],
      colors: ["Tan"],
      sizes: ["One Size"],
      images: ["images/aclothes/canvas-travel-backpack.jpg"],
      description: "Canvas Travel Backpack · Like New condition · listed by Ishaan Verma (ishaan.v). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "everyday-leather-tote",
      name: "Everyday Backpack",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Backpacks",
      price: 600,
      condition: "Like New",
      listedDaysAgo: 7,
      seller: { name: "Kabir Shah", username: "kabir.s", email: "kabir.s@ashoka.edu.in", rating: 4.4, sales: 15, responseRate: 82, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 121,
      popularity: 74,
      isNew: true,
      tags: ["backpack","everyday","leather"],
      colors: ["Tan"],
      sizes: ["One Size"],
      images: ["images/aclothes/everyday-leather-tote.jpg"],
      description: "Everyday Backpack · Like New condition · listed by Kabir Shah (kabir.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "cream-blush-wand",
      name: "Cream Blush Wand",
      brand: "Veridana",
      category: "beauty",
      subcategory: "Makeup",
      price: 500,
      condition: "Fair",
      listedDaysAgo: 11,
      seller: { name: "Meera Nair", username: "meera.n", email: "meera.n@ashoka.edu.in", rating: 4.9, sales: 27, responseRate: 97, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 96,
      popularity: 70,
      isNew: true,
      tags: ["blush","makeup","clean-beauty"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/cream-blush-wand.jpg"],
      description: "Cream Blush Wand · Fair condition · listed by Meera Nair (meera.n). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "burgundy-buckle-shoulder-bag",
      name: "Burgundy Buckle Shoulder Bag",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Shoulder",
      price: 550,
      condition: "Good",
      listedDaysAgo: 22,
      seller: { name: "Nikhil Bose", username: "nikhil.b", email: "nikhil.b@ashoka.edu.in", rating: 4.3, sales: 6, responseRate: 78, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 87,
      popularity: 78,
      isNew: true,
      tags: ["shoulder-bag","buckle","evening"],
      colors: ["Burgundy"],
      sizes: ["One Size"],
      images: ["images/aclothes/burgundy-buckle-shoulder-bag.jpg"],
      description: "Burgundy Buckle Shoulder Bag · Good condition · listed by Nikhil Bose (nikhil.b). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "candle-warmer-lamp",
      name: "Candle Warmer Lamp",
      brand: "Terracotta Tales",
      category: "home",
      subcategory: "Objects",
      price: 650,
      condition: "Like New",
      listedDaysAgo: 12,
      seller: { name: "Aisha Khan", username: "aisha.k", email: "aisha.k@ashoka.edu.in", rating: 4.8, sales: 22, responseRate: 93, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.8,
      reviews: 44,
      popularity: 63,
      isNew: false,
      tags: ["lamp","candle","ambient"],
      colors: ["Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/candle-warmer-lamp.jpg"],
      description: "Candle Warmer Lamp · Like New condition · listed by Aisha Khan (aisha.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "tealight-candle-holder-set",
      name: "Pool Ball Tealight Holder Set",
      brand: "Terracotta Tales",
      category: "home",
      subcategory: "Objects",
      price: 800,
      condition: "Fair",
      listedDaysAgo: 17,
      seller: { name: "Rohit Desai", username: "rohit.d", email: "rohit.d@ashoka.edu.in", rating: 4.5, sales: 11, responseRate: 85, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 39,
      popularity: 51,
      isNew: false,
      tags: ["tealight","candle-holder","set"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/tealight-candle-holder-set.jpg"],
      description: "Pool Ball Tealight Holder Set · Fair condition · listed by Rohit Desai (rohit.d). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "designer-leather-shoulder-bag",
      name: "Designer Leather Shoulder Bag",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Shoulder",
      price: 850,
      condition: "Excellent",
      listedDaysAgo: 14,
      seller: { name: "Sanya Gupta", username: "sanya.g", email: "sanya.g@ashoka.edu.in", rating: 4.7, sales: 16, responseRate: 91, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.8,
      reviews: 132,
      popularity: 82,
      isNew: true,
      tags: ["designer","leather","shoulder"],
      colors: ["Black"],
      sizes: ["One Size"],
      images: ["images/aclothes/designer-leather-shoulder-bag.jpg"],
      description: "Designer Leather Shoulder Bag · Excellent condition · listed by Sanya Gupta (sanya.g). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "new-nudes-palette",
      name: "Pro New Nudes Eye Palette",
      brand: "Veridana",
      category: "beauty",
      subcategory: "Makeup",
      price: 500,
      condition: "Excellent",
      listedDaysAgo: 15,
      seller: { name: "Vivaan Joshi", username: "vivaan.j", email: "vivaan.j@ashoka.edu.in", rating: 4.2, sales: 4, responseRate: 74, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 208,
      popularity: 76,
      isNew: true,
      tags: ["eyeshadow","palette","pro"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/new-nudes-palette.jpg"],
      description: "Pro New Nudes Eye Palette · Excellent condition · listed by Vivaan Joshi (vivaan.j). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "wedding-eye-palette",
      name: "Wedding-Day Eye Palette",
      brand: "Veridana",
      category: "beauty",
      subcategory: "Makeup",
      price: 500,
      condition: "Fair",
      listedDaysAgo: 11,
      seller: { name: "Tara Pillai", username: "tara.p", email: "tara.p@ashoka.edu.in", rating: 4.9, sales: 35, responseRate: 99, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 142,
      popularity: 64,
      isNew: false,
      tags: ["eyeshadow","wedding","pastel"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/wedding-eye-palette.jpg"],
      description: "Wedding-Day Eye Palette · Fair condition · listed by Tara Pillai (tara.p). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "handloom-midi-skirt",
      name: "Designer Indian-Print Bag",
      brand: "Sirohi",
      category: "bags",
      subcategory: "Handbags",
      price: 700,
      condition: "Excellent",
      listedDaysAgo: 27,
      seller: { name: "Arjun Reddy", username: "arjun.r", email: "arjun.r@ashoka.edu.in", rating: 4.6, sales: 18, responseRate: 87, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 52,
      popularity: 58,
      isNew: false,
      tags: ["bag","indian-print","designer"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/handloom-midi-skirt.jpg"],
      description: "Designer Indian-Print Bag · Excellent condition · listed by Arjun Reddy (arjun.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "bloom-print-kurta",
      name: "Sun & Moon Earrings",
      brand: "Boho Threads",
      category: "jewellery",
      subcategory: "Earrings",
      price: 250,
      condition: "Excellent",
      listedDaysAgo: 2,
      seller: { name: "Zoya Sheikh", username: "zoya.s", email: "zoya.s@ashoka.edu.in", rating: 4.8, sales: 13, responseRate: 94, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 74,
      popularity: 66,
      isNew: true,
      tags: ["celestial","earrings","gold"],
      colors: ["Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/bloom-print-kurta.jpg"],
      description: "Sun & Moon Earrings · Excellent condition · listed by Zoya Sheikh (zoya.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "printed-fleece-hoodie",
      name: "Celestial Bodies Necklace",
      brand: "Artisanal Threads",
      category: "jewellery",
      subcategory: "Necklaces",
      price: 500,
      condition: "Excellent",
      listedDaysAgo: 27,
      seller: { name: "Dev Malhotra", username: "dev.m", email: "dev.m@ashoka.edu.in", rating: 4.4, sales: 9, responseRate: 80, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 46,
      popularity: 47,
      isNew: false,
      tags: ["necklace","celestial","gold"],
      colors: ["Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/printed-fleece-hoodie.jpg"],
      description: "Celestial Bodies Necklace · Excellent condition · listed by Dev Malhotra (dev.m). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "bandhani-co-ord",
      name: "Bandhani Print Co-ord",
      brand: "Rangoli Studio",
      category: "clothing",
      subcategory: "Sets",
      price: 200,
      condition: "Excellent",
      listedDaysAgo: 15,
      seller: { name: "Kavya Rao", username: "kavya.r", email: "kavya.r@ashoka.edu.in", rating: 4.7, sales: 21, responseRate: 92, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 83,
      popularity: 72,
      isNew: true,
      tags: ["co-ord","bandhani","silk-touch"],
      colors: ["Yellow"],
      sizes: ["40"],
      images: ["images/aclothes/bandhani-co-ord.jpg"],
      description: "Bandhani Print Co-ord · Excellent condition · listed by Kavya Rao (kavya.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "leather-crossbody-mini",
      name: "Indian Maxi Skirt",
      brand: "Mirabeau",
      category: "clothing",
      subcategory: "Skirts",
      price: 350,
      condition: "Excellent",
      listedDaysAgo: 3,
      seller: { name: "Yash Patel", username: "yash.p", email: "yash.p@ashoka.edu.in", rating: 4.3, sales: 7, responseRate: 76, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 61,
      popularity: 60,
      isNew: false,
      tags: ["maxi-skirt","indian-print","ethnic"],
      colors: ["Multicolour"],
      sizes: ["38"],
      images: ["images/aclothes/leather-crossbody-mini.jpg"],
      description: "Indian Maxi Skirt · Excellent condition · listed by Yash Patel (yash.p). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "oxidised-jhumka-set",
      name: "Clockwork Heels",
      brand: "Atelier Moti",
      category: "shoes",
      subcategory: "Heels",
      price: 1000,
      condition: "Excellent",
      listedDaysAgo: 2,
      seller: { name: "Mira Sen", username: "mira.s", email: "mira.s@ashoka.edu.in", rating: 4.9, sales: 29, responseRate: 96, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 92,
      popularity: 68,
      isNew: true,
      tags: ["heels","clockwork","statement"],
      colors: ["Gold"],
      sizes: ["UK 5"],
      images: ["images/aclothes/oxidised-jhumka-set.jpg"],
      description: "Clockwork Heels · Excellent condition · listed by Mira Sen (mira.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "block-print-cushion-duo",
      name: "Silver Mesh Heels",
      brand: "Terracotta Tales",
      category: "shoes",
      subcategory: "Heels",
      price: 1000,
      condition: "Like New",
      listedDaysAgo: 13,
      seller: { name: "Neel Bhatia", username: "neel.b", email: "neel.b@ashoka.edu.in", rating: 4.5, sales: 14, responseRate: 84, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 37,
      popularity: 42,
      isNew: false,
      tags: ["heels","mesh","party"],
      colors: ["Silver"],
      sizes: ["UK 4"],
      images: ["images/aclothes/block-print-cushion-duo.jpg"],
      description: "Silver Mesh Heels · Like New condition · listed by Neel Bhatia (neel.b). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "chiffon-dupatta",
      name: "Maroon Fish-Eye Leather Heels",
      brand: "Sirohi",
      category: "shoes",
      subcategory: "Heels",
      price: 950,
      condition: "Excellent",
      listedDaysAgo: 2,
      seller: { name: "Ananya Gokhale", username: "ananya.g", email: "ananya.g@ashoka.edu.in", rating: 4.8, sales: 17, responseRate: 93, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 43,
      popularity: 45,
      isNew: false,
      tags: ["heels","leather","maroon"],
      colors: ["Maroon"],
      sizes: ["UK 5"],
      images: ["images/aclothes/chiffon-dupatta.jpg"],
      description: "Maroon Fish-Eye Leather Heels · Excellent condition · listed by Ananya Gokhale (ananya.g). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "embroidered-festive-flats",
      name: "Blush Liquid Tint",
      brand: "Charmpad Studio",
      category: "beauty",
      subcategory: "Makeup",
      price: 200,
      condition: "Like New",
      listedDaysAgo: 13,
      seller: { name: "Riya Chatterjee", username: "riya.c", email: "riya.c@ashoka.edu.in", rating: 4.6, sales: 10, responseRate: 89, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 57,
      popularity: 61,
      isNew: true,
      tags: ["blush","makeup","liquid-tint"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/embroidered-festive-flats.jpg"],
      description: "Blush Liquid Tint · Like New condition · listed by Riya Chatterjee (riya.c). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "satin-quilted-pouch",
      name: "Eyeshadow Palette",
      brand: "Swadeshi Wares",
      category: "beauty",
      subcategory: "Makeup",
      price: 500,
      condition: "Excellent",
      listedDaysAgo: 3,
      seller: { name: "Aditi Rao", username: "aditi.r", email: "aditi.r@ashoka.edu.in", rating: 4.9, sales: 31, responseRate: 98, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 48,
      popularity: 43,
      isNew: false,
      tags: ["eyeshadow","palette","makeup"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/satin-quilted-pouch.jpg"],
      description: "Eyeshadow Palette · Excellent condition · listed by Aditi Rao (aditi.r). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "handpainted-boho-blouse",
      name: "Clay Hand-Painted Earrings",
      brand: "Rangoli Studio",
      category: "jewellery",
      subcategory: "Earrings",
      price: 300,
      condition: "Excellent",
      listedDaysAgo: 3,
      seller: { name: "Ananya Iyer", username: "ananya.i", email: "ananya.i@ashoka.edu.in", rating: 4.8, sales: 12, responseRate: 95, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 63,
      popularity: 57,
      isNew: true,
      tags: ["clay","earrings","handpainted"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/handpainted-boho-blouse.jpg"],
      description: "Clay Hand-Painted Earrings · Excellent condition · listed by Ananya Iyer (ananya.i). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "mango-wood-decor",
      name: "Tulip Pearl Earrings",
      brand: "Terracotta Tales",
      category: "jewellery",
      subcategory: "Earrings",
      price: 300,
      condition: "Like New",
      listedDaysAgo: 13,
      seller: { name: "Rhea Kapoor", username: "rhea.k", email: "rhea.k@ashoka.edu.in", rating: 4.7, sales: 19, responseRate: 90, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.4,
      reviews: 35,
      popularity: 39,
      isNew: false,
      tags: ["pearl","tulip","earrings"],
      colors: ["Pearl"],
      sizes: ["One Size"],
      images: ["images/aclothes/mango-wood-decor.jpg"],
      description: "Tulip Pearl Earrings · Like New condition · listed by Rhea Kapoor (rhea.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "silk-mix-stole",
      name: "Ocean-Scented Candles",
      brand: "Boho Threads",
      category: "home",
      subcategory: "Scent",
      price: 750,
      condition: "Fair",
      listedDaysAgo: 5,
      seller: { name: "Diya Menon", username: "diya.m", email: "diya.m@ashoka.edu.in", rating: 5, sales: 8, responseRate: 100, responseTime: "within an hour", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.5,
      reviews: 56,
      popularity: 49,
      isNew: true,
      tags: ["candle","ocean","home"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/silk-mix-stole.jpg"],
      description: "Ocean-Scented Candles · Fair condition · listed by Diya Menon (diya.m). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "slouchy-leather-handbag",
      name: "Slouchy Denim Handbag",
      brand: "Mirabeau",
      category: "bags",
      subcategory: "Handbags",
      price: 550,
      condition: "Like New",
      listedDaysAgo: 18,
      seller: { name: "Ishaan Verma", username: "ishaan.v", email: "ishaan.v@ashoka.edu.in", rating: 4.6, sales: 24, responseRate: 88, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 66,
      popularity: 59,
      isNew: false,
      tags: ["handbag","denim","slouchy"],
      colors: ["Denim"],
      sizes: ["One Size"],
      images: ["images/aclothes/slouchy-leather-handbag.jpg"],
      description: "Slouchy Denim Handbag · Like New condition · listed by Ishaan Verma (ishaan.v). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "polymer-clay-earrings",
      name: "Polymer Clay Earrings",
      brand: "Kala Kendra",
      category: "jewellery",
      subcategory: "Earrings",
      price: 600,
      condition: "Fair",
      listedDaysAgo: 29,
      seller: { name: "Kabir Shah", username: "kabir.s", email: "kabir.s@ashoka.edu.in", rating: 4.4, sales: 15, responseRate: 82, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 89,
      popularity: 65,
      isNew: true,
      tags: ["polymer-clay","handmade","statement"],
      colors: ["Multicolour"],
      sizes: ["One Size"],
      images: ["images/aclothes/polymer-clay-earrings.jpg"],
      description: "Polymer Clay Earrings · Fair condition · listed by Kabir Shah (kabir.s). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "jules-blazer",
      name: "YSL Lipstick",
      brand: "Estrella",
      category: "beauty",
      subcategory: "Makeup",
      price: 500,
      condition: "Excellent",
      listedDaysAgo: 3,
      seller: { name: "Meera Nair", username: "meera.n", email: "meera.n@ashoka.edu.in", rating: 4.9, sales: 27, responseRate: 97, responseTime: "within a few hours", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.7,
      reviews: 54,
      popularity: 55,
      isNew: false,
      tags: ["lipstick","makeup","luxe"],
      colors: [],
      sizes: ["One Size"],
      images: ["images/aclothes/jules-blazer.jpg"],
      description: "YSL Lipstick · Excellent condition · listed by Meera Nair (meera.n). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "lorelai-co-ord",
      name: "Vintage Phone Ring",
      brand: "Boho Threads",
      category: "accessories",
      subcategory: "Phone",
      price: 150,
      condition: "Excellent",
      listedDaysAgo: 8,
      seller: { name: "Nikhil Bose", username: "nikhil.b", email: "nikhil.b@ashoka.edu.in", rating: 4.3, sales: 6, responseRate: 78, responseTime: "within a day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.6,
      reviews: 61,
      popularity: 52,
      isNew: false,
      tags: ["phone-ring","vintage","accessory"],
      colors: ["Gold"],
      sizes: ["One Size"],
      images: ["images/aclothes/lorelai-co-ord.jpg"],
      description: "Vintage Phone Ring · Excellent condition · listed by Nikhil Bose (nikhil.b). Pick up on campus: coordinate the handoff with the seller after checkout."
    },
    {
      id: "vintage-lily-lamp",
      name: "Vintage Lily Table Lamp",
      brand: "Terracotta Tales",
      category: "home",
      subcategory: "Lighting",
      price: 450,
      condition: "Excellent",
      listedDaysAgo: 15,
      seller: { name: "Aisha Khan", username: "aisha.k", email: "aisha.k@ashoka.edu.in", rating: 4.8, sales: 22, responseRate: 93, responseTime: "same day", university: 'Ashoka University' },
      originalPrice: null,
      rating: 4.8,
      reviews: 71,
      popularity: 67,
      isNew: true,
      tags: ["lamp","vintage","lily"],
      colors: ["Cream"],
      sizes: ["One Size"],
      images: ["images/aclothes/vintage-lily-lamp.jpg"],
      description: "Vintage Lily Table Lamp · Excellent condition · listed by Aisha Khan (aisha.k). Pick up on campus: coordinate the handoff with the seller after checkout."
    }
  ];

  const CATEGORY_META = {
    clothing:    { name: 'Clothing',          icon: 'dress',   tagline: 'The student closet', weight: 1 },
    shoes:       { name: 'Footwear',          icon: 'shoe',    tagline: 'Sneakers, heels & more', weight: 2 },
    bags:        { name: 'Bags',              icon: 'bag',     tagline: 'Carry it on', weight: 3 },
    jewellery:   { name: 'Jewellery',         icon: 'ring',    tagline: 'Little treasures', weight: 4 },
    beauty:      { name: 'Beauty',            icon: 'flower',  tagline: 'Self-care shelf', weight: 5 },
    accessories: { name: 'Accessories',       icon: 'glasses', tagline: 'Finishing touches', weight: 6 },
    home:        { name: 'Dorm & Decor',      icon: 'home',    tagline: 'For your room', weight: 7 },
    books:       { name: 'Books & Academics', icon: 'book',    tagline: 'Study essentials', weight: 8 }
  };

  /* materialise the discount field (per requirement) */
  PRODUCTS.forEach(p => {
    p.discount = p.originalPrice ? Math.round((1 - p.price / p.originalPrice) * 100) : 0;
  });

  window.CATEGORY_META = CATEGORY_META;
  window.COUPONS = {
    FLEUR10:  { kind: 'percent', value: 10, label: '10% off · FLEUR10' },
    BLOOM15:  { kind: 'percent', value: 15, minSpend: 4999, label: '15% off · BLOOM15' },
    PETAL20:  { kind: 'percent', value: 20, minSpend: 9999, label: '20% off · PETAL20' },
    FREESHIP: { kind: 'shipping', value: 0, label: 'Free delivery · FREESHIP' }
  };

  window.PRODUCTS = PRODUCTS;

  window.getProduct = function (id) {
    return PRODUCTS.find(function (p) { return p.id === id; }) || null;
  };

  window.relatedProducts = function (product, count) {
    var list = PRODUCTS.filter(function (p) {
      return p.id !== product.id && p.category === product.category;
    });
    if (list.length < count) {
      list = list.concat(PRODUCTS.filter(function (p) {
        return list.indexOf(p) === -1 && p.id !== product.id;
      }));
    }
    return list.slice(0, count);
  };
})();
